version: '3.8'

services:
  flask-app:
    build: ./app
    ports:
      - "5000:5000"
    networks:
      - nginx-net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - flask-app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx-net

networks:
  nginx-net:
    driver: bridge